### PR TITLE
Fixed leaderboard profile pics

### PR DESCRIPTION
**Pull request by jhan25**
Replaced img tags with div (background image)

### CODE REVIEW

**Comment by nkansal96** [comment]
We should make them `.jsx`. What were the issues specifically?

**Comment by howardwang15** [comment]
image

I looked at the webpack.config file and babel is there for importing jsx files...not sure why this error occurs

**Comment by nkansal96** [comment]
Does this error still happen if you re-start web pack after renaming the file?

**Comment by howardwang15** [comment]
Ah that worked

**Comment by nkansal96** [comment]
@howardwang15 in the past I haven't been consistent about this. Though I prefer the `export default` at class definition, if you are planning on adopting `PropTypes` for all components, then export separately at the bottom.

**Pull request merged**
