### PR TITLE
Added leaderboard modal

### PR DESCRIPTION
**Pull request by jhan25**
Clicking on either name or profile picture of user in leaderboard should bring up modal with that user's info.
Info includes name, major, and year.
modal1

### CODE REVIEW

**Comment by howardwang15** [comment]
@jhan25  The modal looks good...can you make the modal show up when you click the top users as well? Maybe attach an onClock prop to the TopUser component?

**Comment by jhan25** [comment]
Oh that's really odd, I'm sure I implemented it so that the modal would appear for top users too..
Let me take a look :/

**Comment by jhan25** [comment]
Aite got it fixed! :+1:

**Comment by howardwang15** [comment]
Merging this

**Pull request merged**
